### ISSUE TITLE
#whatissaturn url fragment flickers in the url bar on first page load

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/homepage#150]
quite minor bug: when you navigate to https://strn.network/, the fragment https://strn.network/#whatissaturn flickers before being removed

to repro:
1. open new tab
2. load https://strn.network/
3. watch the url bar: https://strn.network/#whatissaturn flickers quickly before being replaced with the correct https://strn.network/ (sans fragment)

the correct behavior should be no flicker of https://strn.network/#whatissaturn

**Comment by benjaminpreiss** [comment]
This should be fixed as a side effect of commit b6b456ad2e84db320454a35cda31ce7af968a5db. At least I can't replicate it anymore.
