### ISSUE TITLE
preserve the url path when redirecting from strn.network to saturn.tech

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/homepage#183]
the path is dropped from the 301 redirect form strn.network to saturn.tech when it should be preserved

i tested both `strn.network` and subdomains, like `dashboard.strn.network`. both fail to preserve url path

ex:

`strn.network/whatever` -> `saturn.tech`
```
% curl -sI https://strn.network/whatever | grep -i location
Location: https://saturn.tech
```

`dashboard.strn.network/address/all` -> `dashboard.saturn.tech`

```
% curl -I https://dashboard.strn.network/address/all | grep -i location
Location: https://dashboard.saturn.tech
```

i tagged this issue as high priority because these are 301 permanent redirects. so we want to fix this asap to prevent browsers from remembering the wrong redirect

**Comment by guanzo** [comment]
Fixed

```sh
$ curl -sI https://strn.network/whatever | grep -i location
location: https://saturn.tech/whatever
$ curl -sI https://dashboard.strn.network/address/all | grep -i location
location: https://dashboard.saturn.tech/address/all
```

**Comment by gruns** [comment]
awesome. ty! 🙌
