### ISSUE TITLE
improve the loading speed of the metrics on the homepage

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/homepage#185]
so these metrics

![image](https://github.com/filecoin-saturn/homepage/assets/1041265/08a8c77c-c759-48b7-8dc1-d138f6ee83b5)

load nigh instantly

right now to load these three metrics the page fetches

  * https://uc2x7t32m6qmbscsljxoauwoae0yeipw.lambda-url.us-west-2.on.aws/?filAddress=all&step=day&startDate=1686224460235&endDate=1686310860235

which is a 600kb json blob that includes *everything* about the network. this file also takes over 5 seconds to load

![image](https://github.com/filecoin-saturn/homepage/assets/1041265/85e9b033-0521-47f4-8fb6-6221350d8927)

instead, fetch a much smaller, faster file to load these three metrics nigh instantly

potential solutions:
* create a new orchestrator api endpoint
* modify this lambda
* create a new lambda

**Comment by guanzo** [comment]
https://github.com/filecoin-saturn/L1-dashboard/pull/45
https://github.com/filecoin-saturn/log-ingestor/pull/72

**Comment by gruns** [comment]
@guanzo
1. awesome changes with https://github.com/filecoin-saturn/L1-dashboard/pull/45 and https://github.com/filecoin-saturn/log-ingestor/pull/72 💪 
2. this didnt fix the issue; homepage stats still load slowly, taking ~2.5-3s to load
3. is a deploy required to push these changes with `&perNode=false` live?

i just tested with and without `&perNode=false`. here's without `&perNode=false`:

```
% time curl -sI 'https://uc2x7t32m6qmbscsljxoauwoae0yeipw.lambda-url.us-west-2.on.aws/?filAddress=all&step=day&startDate=1686565257290&endDate=1686651657290'
HTTP/1.1 200 OK
Date: Tue, 13 Jun 2023 10:24:42 GMT
Content-Type: application/json
Content-Length: 0
Connection: keep-alive
x-amzn-RequestId: de8ea7e7-d7de-4849-b173-80634f47cc18
X-Amzn-Trace-Id: root=1-648843e9-75b7c29f367a1372558dff5a;sampled=0;lineage=7587817c:0

curl -sI   0.03s user 0.01s system 1% cpu 2.415 total
```

and with `&perNode=false`:

```
% time curl -sI 'https://uc2x7t32m6qmbscsljxoauwoae0yeipw.lambda-url.us-west-2.on.aws/?filAddress=all&step=day&startDate=1686565257290&endDate=1686651657290&perNode=false'
HTTP/1.1 200 OK
Date: Tue, 13 Jun 2023 10:24:50 GMT
Content-Type: application/json
Content-Length: 0
Connection: keep-alive
x-amzn-RequestId: 2643f86b-c445-46e2-8a60-f644f3a43470
X-Amzn-Trace-Id: root=1-648843f0-3d19bbcc7b67d5642b8607a3;sampled=0;lineage=7587817c:0

curl -sI   0.04s user 0.02s system 2% cpu 2.307 total
```

both take ~2.5s and are ~600kb of data

**Comment by guanzo** [comment]
After deploy, response is 1.1KB with ~300ms avg response time.

**Comment by gruns** [comment]
![image](https://github.com/filecoin-saturn/homepage/assets/1041265/529ec3f7-1766-4c77-a6f0-8cb1f826cdd7)

awesome 😎 

the next minor optimization is to `<link rel="preload"...` this content to avoid the 300-500ms queueing delay due to js. or just kick off the fetch in js earlier. but that's for a separate, much lower priority issue 

awesome work here, @guanzo 👏
