### ISSUE TITLE
change the network ttfb value of 320ms from a static summary value to one loaded dynamically

### ISSUE THREAD

**Issue by gruns** [filecoin-saturn/homepage#189]
change 320ms from the current static, summary value to a value that's loaded dynamically on page load

the lambda behind the homepage can pull these stats from the same source as https://explorer.saturn.tech/

![image](https://github.com/filecoin-saturn/homepage/assets/1041265/6e68f2af-0c8f-48f2-909b-a9b9eaf44d1f)

**Comment by gruns** [comment]
@gitstart 

these ttfb latencies are now retrievable via the same APIs that the [explorer](https://github.com/filecoin-saturn/explorer) uses. as such, please file a PR to fetch these ttfb on the homepage and display it appropriately 🙏 

thank you! 🙌 

![image](https://github.com/filecoin-saturn/homepage/assets/1041265/8aedf3ca-731f-4333-ab2e-46907fc799f6)

**Comment by guanzo** [comment]
This was already done, just missing the last piece https://github.com/filecoin-saturn/homepage/commit/dd653b75facb64366eb8e8dea96a39e25af38011

**Comment by gruns** [comment]
💪
